### PR TITLE
fix(doc): Use correct LTR/RTL Fela renderer in renderComponent

### LINKED ISSUE #24: RTL mode does not work properly
### Steps
1. add `marginRight: <some_value>` style to any component implementation
2. add a docs example that takes this component
3. press the `RTL` button
screen shot 2018-07-30 at 15 46 56
4. inspect the component

### Expected Result
CSS prop `marginRight: <some_value>` is changed to `marginLeft: <some_value>`

### Actual Result
CSS `marginRight: <some_value>` does not change to `marginLeft`!

### Version
0.2.3

### PR DESCRIPTION
**Pull request by miroslavstastny**
fixes #24

# [RTL component preview in Docs]

When component preview in Docs is switched to RTL, two things happen:

1. the component is wrapped by `<div dir="rtl">`.
2. Fela renderer with RTL plugin is used.

The problem was that `getClasses()` used hardcoded LTR Fela renderer regardless the switch.
Now renderer is added to fela theme and `getClasses()` uses the renderer from the theme (via context).

### TODO

- [ ] Update the CHANGELOG.md

### CODE REVIEW

File: src/components/Provider/Provider.tsx [hunk 1]
```diff
@@ -36,22 +36,26 @@ class Provider extends Component<any, any> {
 
   static Consumer = ProviderConsumer
 
-  renderStaticStyles = felaRenderer => {
+  renderStaticStyles = () => {
+    // RTL WARNING
```
Comment (kuzhelov) [inline src/components/Provider/Provider.tsx]: maybe it would be a good idea to include reference on docs where it is stated that
> no further processing with plugins will be done for static styles

http://fela.js.org/docs/advanced/StaticStyle.html

Comment (miroslavstastny) [reply src/components/Provider/Provider.tsx]: Thanks, link added.
